version: "3.9"
services:
 app:
    build:
      context: .
    container_name: php-website
    restart: unless-stopped
    volumes:
      - app:/php-todo
    ports:
      - "${APP_PORT}:80"
    links:
      - db
    depends_on:
      - db

 db:
    image: mysql/mysql-server:latest
    container_name: php-db-server
    hostname: "${DB_HOSTNAME}"
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    
    ports:
      - "${DB_PORT}:3306"

    volumes:
      - db:/var/lib/mysql

  localtunnel:
    build:
      context: ~/localtunnel
      dockerfile: Dockerfile
    network_mode: tooling_app_network
    restart: unless-stopped
        
        command: --local-host 127.0.0.1 --port 8080 --subdomain docker-projects

volumes:
  app:
  db: